version: "3.7"
services:
  metabase:
    image: metabase/metabase:v0.44.6
    container_name: openpodcast_metabase
    volumes:
      - metabase-data:/metabase-data
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    networks:
      - inter-stack
      - world
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.persistent == extvoldb1

networks:
  inter-stack:
    external: true
  world:

volumes:
  metabase-data:
